version: '3.8'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: social_network
    networks:
      - secure_app_network
    restart: unless-stopped

  php:
    image: php:7.2-apache
    container_name: PHP
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html"
    networks:
      - secure_app_network
    depends_on:
      - mysql
    command: >
      sh -c "docker-php-ext-install mysqli pdo_mysql && docker-php-ext-enable mysqli pdo_mysql && apache2-foreground"

networks:
  secure_app_network:
